inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/*
    - config/initializers/*
